language: go
sudo: false

go:
  - 1.5.1
  - tip

script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic
  - go test -race -v -coverprofile=coverage.out -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
